// src/routes/blogs/+page.svelte
<div class="py-16 text-center sm:py-24">
	<!-- Hero Section -->
	<h1
		class="font-lexend-zetta text-4xl leading-tight font-light tracking-widest sm:text-6xl md:text-7xl"
	>
		DEVAN<br />MCGEER
	</h1>
	<p class="mt-6 text-lg tracking-[0.3em] text-gray-700 sm:text-xl sm:tracking-[0.4em] md:text-2xl">
		SITE RELIABILITY ENGINEER
	</p>
	<a href="/blogs/first" class="tracking-widest hover:text-gray-600">FIRST</a>
</div>

// src/app/blogs/page.tsx
import Link from "next/link";
import { Hero } from "@/components/hero";
import { getAllPosts } from "@/lib/mdx";

export default function BlogIndex() {
  const posts = getAllPosts();

  return (
    <>
      <Hero title="Devan McGeer" subtitle="Blog" />

      <div className="space-y-4">
        {posts.map((post) => (
          <div key={post.slug}>
            <Link
              href={`/blogs/${post.slug}`}
              className="tracking-widest hover:text-gray-600"
            >
              {post.title.toUpperCase()}
            </Link>
            <p className="text-sm text-gray-600">{post.description}</p>
          </div>
        ))}
      </div>
    </>
  );
}
