// src/lib/components/header.svelte
<script lang="ts">
	import Icon from '@iconify/svelte'
</script>

<header class="flex items-center py-6">
	<nav class="w-full items-center justify-between md:flex">
		<div class="hidden text-2xl font-bold tracking-wider md:flex">
			<a href="/">DM</a>
		</div>
		<div class="flex justify-center gap-4">
			<a href="/" class="tracking-widest hover:text-gray-600">HOME</a>
			<a href="/blogs" class="tracking-widest hover:text-gray-600">BLOG</a>
		</div>

		<div class="hidden space-x-4 md:flex">
			<a
				href="https://github.com/McGeerDev"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="GitHub"
			>
				<Icon icon="lucide:github" width="24" height="24" />
			</a>
			<a
				href="https://www.linkedin.com/in/devan-mcgeer/"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="LinkedIn"
			>
				<Icon icon="lucide:linkedin" width="24" height="24" />
			</a>
			<a href="mailto:mcgeer.devan@gmail.com" aria-label="Email">
				<Icon icon="lucide:mail" width="24" height="24" />
			</a>
		</div>
	</nav>
</header>

// src/components/header.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { Github, Linkedin, Mail, Menu, X } from "lucide-react";

const navLinks = [
  { href: "/", label: "HOME" },
  { href: "/blogs", label: "BLOG" },
  { href: "/projects", label: "PROJECTS" },
  { href: "/resume", label: "RESUME" },
];

export function Header() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <header className="flex flex-col py-6">
      <nav className="flex w-full items-center justify-between">
        <div className="hidden text-2xl font-bold tracking-wider md:flex">
          <Link href="/">DM</Link>
        </div>

        <div className="hidden gap-4 md:flex">
          {navLinks.map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className="tracking-widest hover:text-gray-600"
            >
              {link.label}
            </Link>
          ))}
        </div>

        <div className="hidden space-x-4 md:flex">
          <a
            href="https://github.com/McGeerDev"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="GitHub"
          >
            <Github size={24} />
          </a>
          <a
            href="https://www.linkedin.com/in/devan-mcgeer/"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="LinkedIn"
          >
            <Linkedin size={24} />
          </a>
          <a href="mailto:mcgeer.devan@gmail.com" aria-label="Email">
            <Mail size={24} />
          </a>
        </div>

        {/* Mobile */}
        <div className="flex w-full items-center justify-between md:hidden">
          <div className="flex gap-4">
            {navLinks.map((link) => (
              <Link
                key={link.href}
                href={link.href}
                className="text-sm tracking-widest hover:text-gray-600"
              >
                {link.label}
              </Link>
            ))}
          </div>
        </div>
      </nav>
    </header>
  );
}
